# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000



development:
  adapter: postgresql
  database: postgres
  username: dev
  password: ENV[database_password]
test:
  adapter: postgresql
  database: postgres
  username: dev
  password: ENV[database_password]
production:
  adapter: postgresql
  database: postgres
  username: dev
  password: ENV[database_password]